FWTYPE=nftables
SET_MAXELEM=522288
IPSET_OPT="hashsize 256 maxelem 522288"
MODE=nfqws
MODE_HTTP=1
MODE_HTTPS=1
MODE_QUIC=1
MODE_FILTER=autohostlist
NFQWS_OPT=" \
--filter-tcp=80 --dpi-desync=fake,multisplit --dpi-desync-split-pos=method+2 <HOSTLIST> \
--new \
--filter-tcp=443 --dpi-desync=fakedsplit --dpi-desync-ttl=5 --orig-ttl=1 --orig-mod-start=s1 --orig-mod-cutoff=d1 --dpi-desync-split-pos=midsld <HOSTLIST> \
--new \
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 <HOSTLIST_NOAUTO> \
"

